### ISSUE TITLE
Float numbers are RPAD-ded incorrectly

### ISSUE THREAD

**Issue by lukas-vlcek** [lukas-vlcek/elasticsearch-mixin#1]
Take for example the following two cases:
https://github.com/lukas-vlcek/elasticsearch-mixin/blob/c35f1bd73b0ae1e292e5882672e4ed97843c1cf5/dashboards/elasticsearch.libsonnet#L102 and https://github.com/lukas-vlcek/elasticsearch-mixin/blob/c35f1bd73b0ae1e292e5882672e4ed97843c1cf5/dashboards/elasticsearch.libsonnet#L109

After processing these are turned into:
`"value": 0.80000000000000004` and `"value": 0.90000000000000002`.

//cc @brancz - any idea how to fix this?

**Comment by brancz** [comment]
I searched through most of the jsonnet.org website but couldn't find an answer. Maybe @sparkprime can shed some light :slightly_smiling_face: .

**Comment by sparkprime** [comment]
The JSON manifester prints out the floats losslessly, whereas some other languages by default round off the last few digits to try to mask the limitations of floating point.

Open up your javascript console and put in 0.80000000000000004, it will come out as 0.8

This shouldn't matter though - whatever consumes the JSON will interpret 0.8 and 0.80000000000000004 in exactly the same way, since they are indistinguishable within the precision of IEEE double.

**Comment by lukas-vlcek** [comment]
Thanks @sparkprime
